CXX=c++
CXX_FLAGS=-std=c++11 -I./include -DCURRENT_PLATFORM `sdl-config --cflags`   
LD_FLAGS= `sdl-config --libs` -lSDL_ttf
PROGRAM_NAME=Dr.S

all:
	$(CXX) $(CXX_FLAGS) source/$(PROGRAM_NAME).cpp -o cross/$(PROGRAM_NAME) $(LD_FLAGS)
clean:
	rm -f cross/$(PROGRAM_NAME)

run: all
	cd cross && ./$(PROGRAM_NAME) && cd ..
