CXX=c++
CXX_FLAGS= -I./include -DCURRENT_PLATFORM `sdl-config --cflags`   
LD_FLAGS= `sdl-config --libs` -lSDL_ttf -lSDL_image -lSDL_mixer
PROGRAM_NAME=codename_quadtris
PROGRAM_SOURCE=

all:
	$(CXX) $(CXX_FLAGS) source/$(PROGRAM_NAME).cpp $(PROGRAM_SOURCE) -o cross/$(PROGRAM_NAME) $(LD_FLAGS)
clean:
	rm -f cross/$(PROGRAM_NAME)

run: all
	cd cross && ./$(PROGRAM_NAME) && cd ..
